import json
from loguru import logger
from config import NORM_STATS_PATH, CPP_HEADER_PATH, N_CHANNELS, CHANNELS


def generate_cpp_header(norm_path=NORM_STATS_PATH, out_path=CPP_HEADER_PATH):
    with open(norm_path) as f:
        s = json.load(f)

    lines = [
        "#pragma once",
        "#include <array>",
        "#include <string_view>",
        "// Auto-generated by NeroSurrogate — do not edit",
        "namespace NeroSurrogate {",
        f"constexpr int N_CHANNELS = {N_CHANNELS};",
        "constexpr std::array<std::string_view, N_CHANNELS> CHANNEL_NAMES = {{",
    ] + [f'    "{n}",' for n in CHANNELS] + [
        "};",
        "constexpr std::array<float, N_CHANNELS> CHANNEL_MEANS = {{",
    ] + [f"    {m:.8f}f," for m in s["means"]] + [
        "};",
        "constexpr std::array<float, N_CHANNELS> CHANNEL_STDS = {{",
    ] + [f"    {v:.8f}f," for v in s["stds"]] + [
        "};",
        "constexpr float MAX_DEPTH_M = 10.0f;",
        "inline float normalize_channel(float v, int ch) { return (v - CHANNEL_MEANS[ch]) / CHANNEL_STDS[ch]; }",
        "inline float denormalize_depth(float v) { return v * MAX_DEPTH_M; }",
        "} // namespace NeroSurrogate",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    logger.info(f"C++ header → {out_path}")
    return out_path
