### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Flood_Engine)
add_subdirectory(Flood_EngineContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Flood_Engineplugin
    Flood_EngineContentplugin
    QtQuickDesignerComponents)